### PR TITLE
Add reverse_rows option to bitmaptools.readinto

### PR DESCRIPTION
**Pull request by kmatch98**
This is added helper for loading graphics BMP files where the rows are reversed, adding a `reverse_rows` input parameter to `bitmaptools.readinto`.  This supports updates to the `adafruit_imageload` library.

Observed a speedup of about 4x when loading the `purple.bmp`: https://cdn-learn.adafruit.com/assets/assets/000/074/681/original/purple.bmp?1555717198

### CODE REVIEW

**Comment by kmatch98** [comment]
Build is failing for:
```
E: The repository 'https://dl.bintray.com/sbt/debian  Release' is no longer signed.
```

No ideas how to resolve this one....

**Review by jepler — APPROVED** [review]
Thanks!

**Comment by jepler** [comment]
Oh look, conflicts.  Do you want to wait on adding this until after the original PR gets merged?  Due to the addition of auto code formatting, the code all got changed out from under us.  Progress!

**Comment by kmatch98** [comment]
No problem at all. I’ll await for when the PR gets merged and figure out how to merge this into that.

**Comment by kmatch98** [comment]
Moved to here:  https://github.com/adafruit/circuitpython/pull/4428

**Pull request closed without merging**
